services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ZIO-HTTP-USERS
    environment:
      - INTERFACE_CONFIG_HOST=localhost
      - INTERFACE_CONFIG_PORT=8080
      - DB_URL=jdbc:postgresql://postgres:5432/zio-http-users
      - DB_USER=lekovv
      - DB_PASSWORD=1315
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - zio-http-users

  postgres:
    image: 'postgres:latest'
    container_name: PostgreSQL
    environment:
      POSTGRES_DB: zio-http-users
      POSTGRES_USER: lekovv
      POSTGRES_PASSWORD: 1315
    ports:
      - "5432:5432"
    networks:
      - zio-http-users

networks:
  zio-http-users:
    driver: bridge
